language: node_js

cache: yarn

node_js:
  - 'stable'
  - '10'
  - '12'

sudo: false

before_script:
  - export NODE_OPTIONS=–max_old_space_size=8192

script:
  - yarn test

deploy:
  - provider: npm
    email: 'thanarie@gmail.com'
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
      node: 'stable'
    skip_cleanup: true
