language: node_js

cache: yarn

node_js:
  - 'stable'
  - '12'

sudo: false

script:
  - yarn test

deploy:
  - provider: npm
    email: 'thanarie@gmail.com'
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
      node: '12'
    skip_cleanup: true
